### ISSUE TITLE
Please fix light status bar icon colors and battery level text alignment

### ISSUE THREAD

**Issue by jahirfiquitiva** [paphonbth/CustomBatteryMeter#2]
In Marshmallow, when apps enable light status bar, the icon colors are wrong:
1. The outside circle is white.
2. The circle inside is full black.

As you can see in the screenshot, both colors are semitransparent black, one more transparent than the other, but the level indicator is never full black.

Also, I'm not sure if I'm the only one, but I see alignment issues when the battery level inside the icon is enabled. As you can see, the text is moved a bit too much to the right.

I'm using latest CM nightly btw.

Thank you, and thanks for this great module.

![screenshot_20160620-182613 01](https://cloud.githubusercontent.com/assets/10360816/16213525/a59ad394-3715-11e6-96f1-056ed2390bba.png)
![screenshot_20160620-183313 01](https://cloud.githubusercontent.com/assets/10360816/16213524/a59a3ed4-3715-11e6-87e3-5ce1e3033bb5.png)

**Comment by jahirfiquitiva** [comment]
I think text aligment issue is a bit more noticeable and/or visible with this one

![screenshot_20160620-195128 01](https://cloud.githubusercontent.com/assets/10360816/16214708/b99124a6-3720-11e6-847d-8758560caea8.png)

**Comment by suphon-t** [comment]
Fixed in v2.

**Comment by jahirfiquitiva** [comment]
This isn't really fixed.

Alignment issue is still present:
![screenshot_20160715-163630-01](https://cloud.githubusercontent.com/assets/10360816/16993299/5953e81c-4e68-11e6-8713-2aeafb3c5e51.png)

And color issue too:
![screenshot_20160715-162809-01](https://cloud.githubusercontent.com/assets/10360816/16993276/43f0406a-4e68-11e6-84db-691777c92ee1.png)

About the color one, you can see the inner circle color is darker than the color other status bar icons use. (Use a color picker app, if you can't see it at first sight).

Thanks for this awesome module, but please fix these things.

**Comment by suphon-t** [comment]
I didn't use a light enough statusbar to test so I didn't see that different. Will try a different method to fix it.

**Comment by jahirfiquitiva** [comment]
Any news?

**Comment by suphon-t** [comment]
I'm very busy recently. Next update will fix this and Xperia crashes.

**Comment by Gotolei** [comment]
Aw, I was watching this.

...while this is bumped, and assuming this project isn't dead, might I piggyback on this kind of request by asking for an option to change spacing around the icon itself? It's a bit tight on the left when compared to everything else.
![untitled](https://cloud.githubusercontent.com/assets/7553595/22623004/2e9fbf86-eb09-11e6-8c7a-e7841839fb90.png)

**Comment by suphon-t** [comment]
I may consider this. Thanks.
